services:
  openapi-mcp-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAPI_TOKEN=${OPENAPI_TOKEN}
    volumes:
      - ./teable-openapi.json:/app/teable-openapi.json